### ISSUE TITLE
NBMiner won't work with the new 21.4.1 Radeon Software Adrenalin

### ISSUE THREAD

**Issue by Chaotix404** [NebuTech/NBMiner#280] opened 2021-04-21 21:26 UTC
When i tried using NBMiner (even with default settings) after installing 21.4.1 on my RX 570 i got this error:

Error load opencl module: clBuildProgram
WARN - QMutex: destroying locked mutex
[19:32:13] ERROR - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[19:32:13] ERROR - Mining program unexpected exit.
[19:32:13] ERROR - Code: 1, Reason: Unknown error
[19:32:13] ERROR - Restart miner after 10 secs ...
[19:32:13] ERROR - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

So i rolled back to the older version, hopefully this get fixed next update 👍

**Comment by kevinpawsey** [comment] 2021-04-22 11:08
I can confirm that I am seeing this same error since upgrading to 21.4.1 on an RX 580, so it does seem to be a driver issue.

I have had to switch to nanominer for now, which is nowhere near as fast an nbminer.

**Comment by roma07-unit** [comment] 2021-04-23 00:37
@Chaotix404 I tried to roll back to the older AMD version but I must not be doing it correctly. My error code says DAG verification failed. Can you explain how you rolled back to the previous AMD version? Thanks!

**Comment by kevinpawsey** [comment] 2021-04-23 07:29
I haven't rolled back myself, but did you use DDU to completely remove the new drivers before installing the previous version?

**Comment by nebutech-admin** [comment] 2021-04-24 09:01
fixed in 37.2

**Closed** 2021-04-24 09:01 UTC
