### ISSUE TITLE
Password parameter issue

### ISSUE THREAD

**Issue by pinpins** [NebuTech/NBMiner#132] opened 2020-03-01 08:12 UTC
Hello,

Users report that password parameters is not being passed towards pool when using comma in it
See as example below
`nbminer.exe  --no-watchdog --no-nvml --temperature-limit 95 -d 0,1 --api 127.0.0.1:4069 -o stratum+tcp://ethash.mine.zergpool.com:9999 -u 134bw4oTorEJUUVFhokDQDfNqTs7rBMNYy:ID=003,c=BTC,mc=PIRL -a ethash`

**Comment by moppidoo** [comment] 2020-03-02 05:58
Hi NBMiner Devs,

in addition, the issue is also reproduced both via direct CLI as well as calling config JSON file (stratum+tcp / ethproxy+tcp made no difference btw)

Miner init via config.json:
![image](https://user-images.githubusercontent.com/9251248/75649202-547a9b00-5ca2-11ea-90b8-af42a931e44d.png)

**Comment by nebutech-admin** [comment] 2020-03-03 02:55
In current versions, ethproxy is not implemented with password support.
We will check that and fix in future versions. Thanks for the report.

**Comment by nebutech-admin** [comment] 2020-03-05 12:49
@moppidoo @pinpins Fixed in 27.5

**Closed by nebutech-admin** 2020-03-05 12:49 UTC
